// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {converter} from '../models';
import {app} from '../models';

export function Convert():Promise<void>;

export function GetSavedOptions():Promise<Array<converter.FromToPair>>;

export function SaveOptions(arg1:Array<app.MyFromToPair>):Promise<void>;

export function SpreadColumns():Promise<Array<string>>;
