// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddOption(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddOption'](arg1, arg2, arg3);
}

export function Convert() {
  return window['go']['app']['App']['Convert']();
}

export function LoadOptions() {
  return window['go']['app']['App']['LoadOptions']();
}

export function RemoveOption(arg1, arg2) {
  return window['go']['app']['App']['RemoveOption'](arg1, arg2);
}

export function SpreadColumns() {
  return window['go']['app']['App']['SpreadColumns']();
}
