// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Convert() {
  return window['go']['app']['App']['Convert']();
}

export function GetSavedOptions() {
  return window['go']['app']['App']['GetSavedOptions']();
}

export function SaveOptions(arg1) {
  return window['go']['app']['App']['SaveOptions'](arg1);
}

export function SpreadColumns() {
  return window['go']['app']['App']['SpreadColumns']();
}
